version: "3"

services:
  user:
    container_name: microservice_user
    build: ./microservice-user
    environment:
      WAIT_HOSTS: microservice_db_user:5432
      PORT: 4001
      HOSTNAME: 0.0.0.0

  database_user:
    container_name: microservice_db_user
    build: ./microservice-db-user
    environment:
      POSTGRES_PASSWORD: "Th1s_Is_p@ssw0rd"

  post:
    container_name: microservice_post
    build: ./microservice-post
    environment:
      WAIT_HOSTS: microservice_db_post:5432
      PORT: 4002
      HOSTNAME: 0.0.0.0

  database_post:
    container_name: microservice_db_post
    build: ./microservice-db-post
    environment:
      POSTGRES_PASSWORD: "Th1s_Is_p@ssw0rd"

  resume:
    container_name: microservice_resume
    build: ./microservice-resume
    environment:
      WAIT_HOSTS: microservice_db_resume:5432
      PORT: 4003
      HOSTNAME: 0.0.0.0

  database_resume:
    container_name: microservice_db_resume
    build: ./microservice-db-resume
    environment:
      POSTGRES_PASSWORD: "Th1s_Is_p@ssw0rd"

  api_gateway:
    container_name: gateway
    build: ./gateway
    environment:
      WAIT_HOSTS: microservice_user:4001, microservice_post:4002, microservice_resume:4003
