version: "3"

services:
  user:
    container_name: microservice_user
    build: ./microservice-user
    environment:
      WAIT_HOSTS: microservice_db_user:5432
      PORT: 4001
      HOSTNAME: 0.0.0.0
      PGHOST: microservice_db_user
      PGUSER: postgres
      PGDATABASE: users
      PGPASSWORD: Th1s_Is_p@ssw0rd
      SECRET: c2VjcmV0VGhhdEVuY3J5cHRXaXRoQmFzZTY0X25hbWVTRVJSRVQ=

  database_user:
    container_name: microservice_db_user
    build: ./microservice-db-user
    environment:
      POSTGRES_PASSWORD: "Th1s_Is_p@ssw0rd"

  post:
    hostname: post
    container_name: microservice_post
    build: ./microservice-post
    environment:
      WAIT_HOSTS: microservice_db_post:5432
      PORT: 4002
      HOSTNAME: 0.0.0.0
      PGHOST: microservice_db_post
      PGUSER: postgres
      PGDATABASE: posts
      PGPASSWORD: Th1s_Is_p@ssw0rd
      SECRET: c2VjcmV0VGhhdEVuY3J5cHRXaXRoQmFzZTY0X25hbWVTRVJSRVQ=

  database_post:
    hostname: db-post
    container_name: microservice_db_post
    build: ./microservice-db-post
    environment:
      POSTGRES_PASSWORD: "Th1s_Is_p@ssw0rd"

  resume:
    hostname: resume
    container_name: microservice_resume
    build: ./microservice-resume
    environment:
      WAIT_HOSTS: microservice_db_resume:5432
      PORT: 4003
      HOSTNAME: 0.0.0.0
      PGHOST: microservice_db_resume
      PGUSER: postgres
      PGDATABASE: resume
      PGPASSWORD: Th1s_Is_p@ssw0rd
      SECRET: c2VjcmV0VGhhdEVuY3J5cHRXaXRoQmFzZTY0X25hbWVTRVJSRVQ=

  database_resume:
    hostname: db-resume
    container_name: microservice_db_resume
    build: ./microservice-db-resume
    environment:
      POSTGRES_PASSWORD: "Th1s_Is_p@ssw0rd"
