version: "3"

services:
  user:
    hostname: user
    container_name: microservice_user
    build: ./microservice-user
    volumes:
      - ./microservice-user/src:/usr/app/src
    environment:
      WAIT_HOSTS: microservice_db_user:5432
      PORT: 4001
      HOSTNAME: 0.0.0.0
    ports:
      - 4001:4001

  database_user:
    hostname: db-user
    container_name: microservice_db_user
    build: ./microservice-db-user
    volumes:
      - ./microservice-db-user/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "Th1s_Is_p@ssw0rd"
    ports:
      - 2346:5432

  post:
    hostname: post
    container_name: microservice_post
    build: ./microservice-post
    volumes:
      - ./microservice-post/src:/usr/app/src
    environment:
      WAIT_HOSTS: microservice_db_post:5432
      PORT: 4002
      HOSTNAME: 0.0.0.0
    ports:
      - 4002:4002

  database_post:
    hostname: db-post
    container_name: microservice_db_post
    build: ./microservice-db-post
    volumes:
      - ./microservice-db-post/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "Th1s_Is_p@ssw0rd"
    ports:
      - 2347:5432

  resume:
    hostname: resume
    container_name: microservice_resume
    build: ./microservice-resume
    volumes:
      - ./microservice-resume/src:/usr/app/src
    environment:
      WAIT_HOSTS: microservice_db_resume:5432
      PORT: 4003
      HOSTNAME: 0.0.0.0
    ports:
      - 4003:4003

  database_resume:
    hostname: db-resume
    container_name: microservice_db_resume
    build: ./microservice-db-resume
    volumes:
      - ./microservice-db-resume/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "Th1s_Is_p@ssw0rd"
    ports:
      - 2348:5432

  api_gateway:
    container_name: gateway
    build: ./gateway
    volumes:
      - ./gateway/src:/usr/app/src
    ports:
      - 4000:4000
