version: "3"

services:
  user:
    container_name: microservice_user
    build:
      context: ./microservice-user
      dockerfile: Docker-CI
    environment:
      WAIT_HOSTS: microservice_db_user:5432
      PORT: 4001
      HOSTNAME: 0.0.0.0
      PGHOST: microservice_db_user
      PGUSER: postgres
      PGDATABASE: users
      PGPASSWORD: Th1s_Is_p@ssw0rd
      PGPORT: 5432
      SECRET: c2VjcmV0VGhhdEVuY3J5cHRXaXRoQmFzZTY0X25hbWVTRVJSRVQ=

  database_user:
    container_name: microservice_db_user
    build: ./microservice-db-user
    environment:
      POSTGRES_PASSWORD: "Th1s_Is_p@ssw0rd"

  post:
    container_name: microservice_post
    build:
      context: ./microservice-post
      dockerfile: Docker-CI
    environment:
      WAIT_HOSTS: microservice_db_post:5432
      PORT: 4002
      HOSTNAME: 0.0.0.0
      PGHOST: microservice_db_post
      PGUSER: postgres
      PGDATABASE: posts
      PGPASSWORD: Th1s_Is_p@ssw0rd
      PGPORT: 5432
      SECRET: c2VjcmV0VGhhdEVuY3J5cHRXaXRoQmFzZTY0X25hbWVTRVJSRVQ=

  database_post:
    container_name: microservice_db_post
    build: ./microservice-db-post
    environment:
      POSTGRES_PASSWORD: "Th1s_Is_p@ssw0rd"

  resume:
    container_name: microservice_resume
    build:
      context: ./microservice-resume
      dockerfile: Docker-CI
    environment:
      WAIT_HOSTS: microservice_db_resume:5432
      PORT: 4003
      HOSTNAME: 0.0.0.0
      PGHOST: microservice_db_resume
      PGUSER: postgres
      PGDATABASE: resume
      PGPASSWORD: Th1s_Is_p@ssw0rd
      PGPORT: 5432
      SECRET: c2VjcmV0VGhhdEVuY3J5cHRXaXRoQmFzZTY0X25hbWVTRVJSRVQ=

  database_resume:
    container_name: microservice_db_resume
    build: ./microservice-db-resume
    environment:
      POSTGRES_PASSWORD: "Th1s_Is_p@ssw0rd"

  api_gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Docker-CI
    environment:
      WAIT_HOSTS: microservice_user:4001, microservice_post:4002, microservice_resume:4003
      USER_URI: http://microservice_user:4001
      POST_URI: http://microservice_post:4002
      RESUME_URI: http://microservice_resume:4003
      SECRET: c2VjcmV0VGhhdEVuY3J5cHRXaXRoQmFzZTY0X25hbWVTRVJSRVQ=
