name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: build docker compose
        run: docker-compose -f docker-compose.ci.yml up -d

      - name: list docker process
        run: docker-compose ps

      - name: run users test
        run: docker exec microservice_user yarn jest

      - name: run posts test
        run: docker exec microservice_post yarn jest

      - name: run resume test
        run: docker exec microservice_resume yarn jest

      - name: run integration test
        run: docker exec gateway yarn jest
